build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

complexity:
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    active: true
    thresholdInObjects: 20

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - "Composable"

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: true
  UnusedImports:
    active: true
  ReturnCount:
    active: true
    max: 4

exceptions:
  TooGenericExceptionCaught:
    active: false
